### ISSUE TITLE
Choose serial number

### ISSUE THREAD

**Issue by MichaelSteg1986** [Waldmensch1/venus.dbus-sma-smartmeter#3]
Hello,
Is it possible to choose the serial number of the sma Energymeter which should used for the Network Transfer Point.
The Problem is i have two Energymeters in the Network.
Thank you

**Comment by Waldmensch1** [comment]
Hi,

I added the serial number filter we discussed in Photovoltaik forum a [while ago ](https://www.photovoltaikforum.com/thread/199433-victron-venusos-treiber-um-sma-em-shm2-0-als-smartmeter-einzubinden/?postID=3636710#post3636710) right now. If you enter your serial number in line 31 of script it will ignore any other serial.
